### ISSUE TITLE
AttributeError: 'module' object has no attribute 'wraps'

### ISSUE THREAD

**Issue by eimajenthat** [scrapinghub/shub#227]
I just installed `shub` from pip with `sudo pip install shub` on a Vagrant VM running Ubuntu Trusty 64-bit.  

I installed it with `sudo`, because I got permission denied errors without it.  I know that's a bad practice, but I don't want to fool with virtualenv.  Besides, it's a vagrant box I created for this specific project, not a production server.

When I run shub, I get: 
```
vagrant@vagrant-ubuntu-trusty-64:~$ shub
Traceback (most recent call last):
  File "/usr/local/bin/shub", line 7, in <module>
    from shub.tool import cli
  File "/usr/local/lib/python2.7/dist-packages/shub/tool.py", line 53, in <module>
    command_module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/shub/image/__init__.py", line 23, in <module>
    command_module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/shub/image/deploy.py", line 132, in <module>
    wait_exponential_max=CHECK_RETRY_EXP_MAX)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 47, in wrap
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
```
Here's my version info:
```
vagrant@vagrant-ubuntu-trusty-64:~$ python --version
Python 2.7.6
vagrant@vagrant-ubuntu-trusty-64:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

I'm sure I'm doing something obvious and stupid, but I don't know what.

**Comment by jdemaeyer** [comment]
Hey Jamie, thanks for the report!

Looks like the version of `six` in Ubuntu's repositories is too old. Can you try updating it with `pip install -U six`?

Btw you don't need to run `pip` as root, but instead can install Python packages into your "user site" with the `--user` flag. E.g. `pip install --user -U six shub`

**Comment by eimajenthat** [comment]
Worked perfectly.  Just had to adjust my path.  Thanks!
